

services:
  postgres:
    container_name: us_demographics_2023
    image: postgres:17.2
    volumes:
      - ../psql_init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: usdemographics 
